name: bigboxx-totem
base: core18
version: git
summary: Totem interface of IoT middleware from e-Cattle platform for livestock farms
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms. This app, named Totem, has the role to provide
  user interface to manage it.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

environment:
  SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: "yes"

apps:
  totem:
    command: http-server -p 3002 $SNAP/dist/
    daemon: simple
    restart-condition: always

plugs:
  home:
  network:
  network-bind:

parts:
  server:
    source: https://github.com/indexzero/http-server.git
    plugin: nodejs
    nodejs-version: 10.16.0
    nodejs-package-manager: npm
  
  totem:
    source: .
    plugin: nil
    override-build: |
      echo "$(</etc/machine-id)" > dist/machine-id.txt
      cp -r dist $SNAPCRAFT_PART_INSTALL/
