name: bigboxx-totem
base: core18
version: git
summary: Totem interface of IoT middleware from e-Cattle platform for livestock farms
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms. This app, named Totem, has the role to provide
  user interface to manage it.
confinement: devmode
grade: devel

environment:
  SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: "yes"

apps:
  totem:
    command: desktop-launch "$SNAP/totem/runner/totem"
    plugs:
    - browser-sandbox
    - network
    - network-bind
    - opengl
    - pulseaudio
    - wayland
    - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
  electron:
    plugin: nodejs
    source: .
    after: [gtk3]
    override-build: |
        case $SNAPCRAFT_ARCH_TRIPLET in
          "i386-linux-gnu") ARCH="ia32";;
          "x86_64-linux-gnu") ARCH="x64";;
          "arm-linux-gnueabihf") ARCH="armv7l";;
          "aarch64-linux-gnu") ARCH="arm64";;
          *) echo "ERROR: electron does not support the '$SNAPCRAFT_ARCH_TRIPLET' architecture" && exit 1;;
        esac
        npm install electron-packager &&
        ./node_modules/.bin/electron-packager dist totem --overwrite --platform=linux --arch=$ARCH --output=release-build --prune=true
        cp -f -v -R ./totem-linux-$ARCH $SNAPCRAFT_PART_INSTALL/runner
    stage-packages:
    - libasound2
    - libgconf-2-4
    - libnss3
    - libx11-xcb1
    - libxss1
    - libxtst6

    build-packages:
    - nodejs
    - npm
    - unzip

  gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5