#!/bin/sh

echo "Configuring system URL"
snap set chromium-mir-kiosk url="http://localhost:3002"

echo "Hidden Cursor"
sudo sed -i "/cursor=software/c cursor=null" /var/snap/mir-kiosk/current/miral-kiosk.config